# config.py

# Binance API 設定（記得替換成你自己的 API Key / Secret）
API_KEY = "YOUR_BINANCE_API_KEY"
API_SECRET = "YOUR_BINANCE_API_SECRET"

# 預設交易參數
BASE_QTY = 0.001       # 每筆下單基礎數量
EQUITY_RATIO = 0.1     # 每次使用資金比例 10%

# 交易幣種池
SYMBOL_POOL = [
    "BTCUSDT", "ETHUSDT", "SOLUSDT", "XRPUSDT", "ADAUSDT",
    "DOGEUSDT", "LINKUSDT", "AVAXUSDT", "MATICUSDT",
    "SUIUSDT", "SEIUSDT", "1000PEPEUSDT", "1000BONKUSDT"
]

# 篩選條件
VOLUME_MIN_USD = 300000
FUNDING_RATE_MIN = -0.05

# 交易策略參數
TREND_EMA_FAST = 12
TREND_EMA_SLOW = 26
MACD_SIGNAL = 9

REVERT_RSI_OVERBOUGHT = 65
REVERT_RSI_OVERSOLD = 35
BOLL_STD_DEV = 2

# K 線設定
KLINE_INTERVAL = "5m"
KLINE_LIMIT = 100

# 風控參數
MAX_LOSS_PCT = 0.3          # 單筆虧損 30% 強制停損
TRAIL_GIVEBACK_PCT = 0.15   # 移動停損回吐 15%

# Railway / Docker 執行參數
DEBUG_MODE = True
