# config.py

# 兩組名稱都提供，避免 ImportError
API_KEY = "YOUR_BINANCE_API_KEY"
API_SECRET = "YOUR_BINANCE_API_SECRET"

BINANCE_API_KEY = API_KEY
BINANCE_API_SECRET = API_SECRET

# 預設交易參數
BASE_QTY = 0.001        # 每筆下單基礎數量（僅做下限保護，實際用 EQUITY_RATIO 算）
EQUITY_RATIO = 0.1      # 每次使用資金比例 10%

# 交易幣種池
SYMBOL_POOL = [
    "BTCUSDT","ETHUSDT","SOLUSDT","XRPUSDT","ADAUSDT",
    "DOGEUSDT","LINKUSDT","AVAXUSDT","MATICUSDT",
    "SUIUSDT","SEIUSDT","1000PEPEUSDT","1000BONKUSDT"
]

# 篩選條件（你說有放寬）
VOLUME_MIN_USD = 300000    # 24h 成交量下限
FUNDING_RATE_MIN = -0.05   # 最低資金費率（允許負值）

# 策略參數
TREND_EMA_FAST = 12
TREND_EMA_SLOW = 26
MACD_SIGNAL = 9

REVERT_RSI_OVERBOUGHT = 65
REVERT_RSI_OVERSOLD = 35
BOLL_STD_DEV = 2

# K 線設定
KLINE_INTERVAL = "5m"
KLINE_LIMIT = 100

# 其他
DEBUG_MODE = True
